### ISSUE TITLE
question

### ISSUE THREAD

**Issue by suqian1988** [ArtLabss/tennis-tracking#13]
Can the tennis-tracking mark the ball bounce position in the video?

thank you very much.
Mike

**Comment by shukkkur** [comment]
@suqian1988 Hi there, thanks for opening the issue! 
Yes, it sure can. 
In README.md I included a gif image where the bounces are **marked in blue**, here

![image](https://user-images.githubusercontent.com/78250180/153860050-72db9991-b505-4e7d-bebb-253f926a419c.png)

If you want all the bounces to be marked on the court, then 👇 
https://github.com/ArtLabss/tennis-tracking/blob/91f0fa2ba740e9840d23c5c0bf3dbeb3b62cbe05/predict_video.py#L337-L339
the list `idx` stores the frame numbers where the ball touches the court. So, change this 
https://github.com/ArtLabss/tennis-tracking/blob/91f0fa2ba740e9840d23c5c0bf3dbeb3b62cbe05/predict_video.py#L357-L370
with this
```python
  while True:
    ret, frame = video.read()
    if ret:
      # if coords[i] is not None:
      for loc in idx:
        center_coordinates = int(xy[loc][0]), int(xy[loc][1])
        radius = 3
        color = (255, 0, 0)
        thickness = -1
        cv2.circle(frame, center_coordinates, 10, color, thickness)
      i += 1
      output_video.write(frame)
    else:
      break
```
Didn't run the code myself, but should work. 
Feel free to reopen the issue, anytime! 
😄

**Comment by suqian1988** [comment]
oh,on the small black court, right?

is there a way to mark the bounce points on the main court?

thank you so much.

Mike.

**Comment by shukkkur** [comment]
@suqian1988  No, the code provided will mark the bounces only on the real court itself. 
As for for marking on the black court (mini-map), it is a bit more complex. We will need the inverse matrix and will then apply perspective transform.
