### ISSUE TITLE
no version of Torch

### ISSUE THREAD

**Issue by nyck33** [ArtLabss/tennis-tracking#16]
**Describe the bug**
Make new conda env with Python=3.8, run pip install -r requirements.txt and get
```
ERROR: Could not find a version that satisfies the requirement torch==1.9.0+cu102 (from versions: 1.4.0, 1.5.0, 1.5.1, 1.6.0, 1.7.0, 1.7.1, 1.8.0, 1.8.1, 1.9.0, 1.9.1, 1.10.0, 1.10.1, 1.10.2, 1.11.0)
ERROR: No matching distribution found for torch==1.9.0+cu102
```
Is `cu` for cuda?  In which case can I run this with another CPU only version of Torch?

**Comment by shukkkur** [comment]
Sorry for late response, have you figured it?

**Comment by nyck33** [comment]
No, I have moved on since.
