### ISSUE TITLE
Question about speed

### ISSUE THREAD

**Issue by 1nv0k3r** [ArtLabss/tennis-tracking#17]
Hi, I have used your algorithm in the official video but it is really slow like 2-3 fps in 3070. I wonder if the high resolution like 1080p video may influence the speed? And it seems that low resolution input video will affect the precison seriously, so what is the suggested resolution balance between speed and accuracy?
BTW, which step do you think is the bottleneck that takes the most time?

**Comment by shukkkur** [comment]
@1nv0k3r Hi! For a detail answer you can have a look at the following file - [performance.txt](https://github.com/ArtLabss/tennis-tracking/files/9297027/performance.txt)

In Summary
- **16.4%** of time takes to detect and track the court 
- **9.7%** to detect the bottom player and **21.3%** for the top player
- **43.8%** takes to detect, track and circle it
