### ISSUE TITLE
Hi, could you provide the training code for the bounce detection ? 

### ISSUE THREAD

**Issue by jaehyunshinML** [ArtLabss/tennis-tracking#18]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by shukkkur** [comment]
@jaehyunshinML Hey there! 
Here is the complete [notebook](https://colab.research.google.com/drive/1wBp4cL4Gr89MwLRdMo25X2sf8rAGSdYJ?usp=sharing), I guess you can find the training code for the bounce in `SKTIME` section of the notebook. Good Luck!

**Comment by nyck33** [comment]
The notebook link is dead, can you fix it?
I want to see if I can transfer learn on your results to get more accuracy.

**Comment by lzh18682334808** [comment]
The links of the training code for the bounce is out of date ,Do you  have a backup? Could you  upload one? Thank you
