### ISSUE TITLE
How is defined the bounce in data for training the model?

### ISSUE THREAD

**Issue by JeanneBod** [ArtLabss/tennis-tracking#22]
In the bigDF.csv, how did you define the bounce?
Is it an observed bounce by an observator visualising of the video?
Thank you for your answer

**Comment by shukkkur** [comment]
Hey @JeanneBod !
I created this `.csv` manually using 9 tennis videos (rallies) and marked the coordinates of bounce (ball touching the court).
Then, before feeding this data to a time series model (`sktime` models) I feature engineered it a bit. Please refer to the following notebook to see all the steps applied to the dataset (**SKTIME** section of the noteboo)
> @jaehyunshinML Hey there! Here is the complete [notebook](https://colab.research.google.com/drive/1wBp4cL4Gr89MwLRdMo25X2sf8rAGSdYJ?usp=sharing), I guess you can find the training code for the bounce in `SKTIME` section of the notebook. Good Luck! And for the record, it's mainly about transforming the dateset into the right format for `sktime`

Feel free to reopen the issue if you will have any additional question :) 
Best of Luck!
