### ISSUE TITLE
Mapping labels to input videos

### ISSUE THREAD

**Issue by eilon1996** [ArtLabss/tennis-tracking#24]
I am having difficulty understanding how the labels in the bigDF.csv and tracking_players.csv files correspond to the frames of the input video files. This is particularly confusing because some of the input videos are missing.

Could you please provide some clarification on this matter?

**Comment by shukkkur** [comment]
Hey @eilon1996 !) 

- `bigDF.csv` was created for training time-series model for bounce detection. As for the videos I used to create that file, I don't have them 
- and `tracking_players.csv` is probably (not my creation / forked) for players. 

I don't understand what you mean by "correspond to the frames"  because they they don't.

**Comment by eilon1996** [comment]
oh I see, I wanted to train my own model to detect the ball location, and
knowing the exact location of the ball in each frame could help me a lot.
Is there any chance that you have that data?

**Comment by shukkkur** [comment]
@eilon1996 `bigDF.csv` contains x/y coordinates of the ball and a Boolean column for bounce:
| x | y | bounce |
| ----------- | ----------- | ----------- |
| x_coordinate    | y_coordinate       | 0 if in the air, else 1 (bounce)|

Note that this `.csv` was put together using different videos  but the order was preserved. 
For example, the rows from 1 to 200 are from the first video, ... I hope you got the point. 

But in case you needed an annotated dataset of tennis balls and bounding boxes, here are tons of datasets - https://universe.roboflow.com/search?q=tennis

![image](https://user-images.githubusercontent.com/78250180/211146384-6dfedccb-cd9e-4ce9-8f02-30ccf712d84e.png)


Feel free to re-open the Issue if further enquire is required.
Best of luck!)

**Comment by eilon1996** [comment]
When you say the first video do you mean video_input2.mp4? 
Because it looks like video_input1.mp4 and video_input7.mp4 are missing. Moreover, the number of frames in all available videos doesn't sum up to the number of rows in the CSV file.

BTW Thanks for the link you attached, but I'm interested in the data you guys have because a ball that was captured in a game doesn't look much like a tennis ball. And more important I can extract more information from a video by checking for example what pixels actually changed in each frame.
