### ISSUE TITLE
Error post tracking ball

### ISSUE THREAD

**Issue by cbutler99** [ArtLabss/tennis-tracking#25]
**Describe the bug**
Node: 'model_1/max_pooling2d/MaxPool
Default MaxPoolingOp only supports NHWC on device type CPU
         [[{{node model_1/max_pooling2d/MaxPool}}]] [Op:__inference_predict_function_1861]

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
Windows 10
Python 3.9
All most upto date libraries as per requirements

**Smartphone (please complete the following information):**

**Additional context**

**Comment by shukkkur** [comment]
@cbutler99 share solution with others for future reference)
