### ISSUE TITLE
NHWC data type on CPU

### ISSUE THREAD

**Issue by Aegislock** [ArtLabss/tennis-tracking#32]
When I run the process.py file with CPU I get this error: 
Node: 'model_1/max_pooling2d/MaxPool'
Default MaxPoolingOp only supports NHWC on device type CPU
	 [[{{node model_1/max_pooling2d/MaxPool}}]] [Op:__inference_predict_function_1861]

**Comment by Aegislock** [comment]
Sorry, meant predict_video.py

**Comment by shukkkur** [comment]
@Aegislock Hey there! Unfortunately, the script won't run on CPU. Please switch to GPU or use Google Colab

**Comment by RylonW** [comment]
sad news! I came up with the same problem.
