### ISSUE TITLE
The training code for the bounce detection is out of date

### ISSUE THREAD

**Issue by LastXuanDog** [ArtLabss/tennis-tracking#33]
Can you reupload the training notebook in [could you provide the training code for the bounce detection](https://github.com/ArtLabss/tennis-tracking/issues/18#issuecomment-1210177886)? The original link is out of date.

**Comment by shukkkur** [comment]
Hi @LastXuanDog !) 
The original notebook was created and stored using my corporate gmail. It has been closed (so has GDrive), and I unfortunately don't have any local backups. Therefore, with my sincerest apologies I am closing this issue :)
