### ISSUE TITLE
-215:Assertion failed) count > 0 in function 'fitLine2D_wods'

### ISSUE THREAD

**Issue by SaiThejeshwar** [ArtLabss/tennis-tracking#7]
Hi,

First of all, this is great work!

This is the error I get when I am trying to run on a tennis video. After printing model summary, this follows.

BOXES  []
BOXES  []
BOXES  [array([166.0948 , 679.272  , 195.11845, 705.8905 ], dtype=float32)]
BIGGEST  [166. 679. 195. 706.]
CAMERA ... Court tracking failed, adding 5 pixels to dist
CAMERA ... Court tracking failed, adding 5 pixels to dist
CAMERA ... Court tracking failed, adding 5 pixels to dist
Traceback (most recent call last):
  File "predict_video.py", line 113, in <module>
    lines = court_detector.track_court(frame)
  File "/content/drive/My Drive/TennisTracking/NewTracking/tennis-tracking/court_detector.py", line 445, in track_court
    return self.track_court(frame)
  File "/content/drive/My Drive/TennisTracking/NewTracking/tennis-tracking/court_detector.py", line 445, in track_court
    return self.track_court(frame)
  File "/content/drive/My Drive/TennisTracking/NewTracking/tennis-tracking/court_detector.py", line 445, in track_court
    return self.track_court(frame)
  File "/content/drive/My Drive/TennisTracking/NewTracking/tennis-tracking/court_detector.py", line 421, in track_court
    [vx, vy, x, y] = cv2.fitLine(new_points, cv2.DIST_L2, 0, 0.01, 0.01)
cv2.error: OpenCV(4.1.2) /io/opencv/modules/imgproc/src/linefit.cpp:50: error: (-215:Assertion failed) count > 0 in function 'fitLine2D_wods'

**Comment by shukkkur** [comment]
@SaiThejeshwar Thanks for writing! Can I see what video you are trying to run the project on?

**Comment by SaiThejeshwar** [comment]
This is the video I am trying to run on https://www.youtube.com/watch?v=CGRzfUccmNE&ab_channel=Wimbledon

**Comment by shukkkur** [comment]
So here is the thing. This project expects a  video (preferably not so long) of the game itself (no commercials, spectators, breaks). Just like the sample [video inputs](https://github.com/ArtLabss/tennis-tracking/tree/main/VideoInput) are. Try trimming that video and passing a single rally to the algorithm. If you do so, let me know how it goes.

**Comment by shukkkur** [comment]
So here is the thing. This project expects a  video (preferably not so long) of the game itself (no commercials, spectators, breaks). Just like the sample [video inputs](https://github.com/ArtLabss/tennis-tracking/tree/main/VideoInput) are. Try trimming that video and passing a single rally to the algorithm. If you do so, let me know how it goes.

**Comment by shukkkur** [comment]
Hi @SaiThejeshwar . Were you able to successfully run the code or still facing any error?

**Comment by SaiThejeshwar** [comment]
Hi @shukkkur . I have trimmed the video to just 2 mins, but looks like there is one logo in between the video. So same error. Will try to trim it and update the results.
